### ISSUE TITLE
Visualisation locomotion with touch booleans

### ISSUE THREAD

**Issue by Matthias2807** [Co-Evolve/brt#8]
For visualization purposes, a useful feature could be that the color of the segments changes to red when the touch boolean for that segment is True. Whether you want this visual feature to be active could be passed on with an argument, similar to the sand_ground_color being turned on or of when instantiating the arena configuration.

**Comment by driesmarzougui** [comment]
All brittle star environment configurations now accept a `color_contacts` argument that enable this. [Example](https://github.com/Co-Evolve/brt/blob/a1bcce3279ff6f23abbdd889f97b166a773c0c98/biorobot/brittle_star/usage_examples/directed_locomotion_single.py#L41)
