### ISSUE TITLE
Target location specification

### ISSUE THREAD

**Issue by Matthias2807** [Co-Evolve/brt#9]
For robustness while training, being able to specify the full polar coordinates of a target could be useful, rather than only specifying the distance between the target and the starting position. Possibly, the argument target_distance in BrittleStarDirectedLocomotionEnvironmentConfiguration class could require a polar coordinates tuple or an additional argument could be added. Either way, if no angle is specified, the position on a circle with radius target_distance around the start position could still be randomly chosen, as is the case now.

**Comment by driesmarzougui** [comment]
Target position can now be passed to the `BrittleStarDirectedLocomotionEnvironmentConfiguration`. [Example](https://github.com/Co-Evolve/brt/blob/a1bcce3279ff6f23abbdd889f97b166a773c0c98/biorobot/brittle_star/usage_examples/directed_locomotion_single.py#L40)
